### ISSUE TITLE
Running a clone has no stats for cpu or mem

### ISSUE THREAD

**Issue by AddictArts** [ningt/iStats#3]
![nothing](https://cloud.githubusercontent.com/assets/911906/17910179/a367f3c8-693c-11e6-97c3-a507230eab2d.png)

Thanks for this project. Looking forward to it once I get it working.

**Comment by ningt** [comment]
Can you provide your OS version and also a screenshot of `top` command?

**Comment by AddictArts** [comment]
I am using Yosemite 10.10.5

![top](https://cloud.githubusercontent.com/assets/911906/17937079/c27b2872-69d5-11e6-8415-c286a2405e58.png)

**Comment by ningt** [comment]
Basically this app uses [os-usage](https://github.com/ningt/os-usage) module to retrieve os and memory usage. The [os-usage](https://github.com/ningt/os-usage) basically is a wrapper of `top` command. It seems you have a different `top` version, would like to look into [os-usage](https://github.com/ningt/os-usage) and submit a PR? Or you can tell me about your `top` version and later I will go fix it.

Thank you!

**Comment by ningt** [comment]
I will close this issue first, we can discuss it at [here](https://github.com/ningt/iStats/issues/1).
