### ISSUE TITLE
npm start generates [warn] kq_init: detected broken kqueue ... 

### ISSUE THREAD

**Issue by 2sama** [ningt/iStats#6]
I installed the iStats using the recommended instructions, however, after running the `npm start`, I get the below error on Mac terminal:

> iStats@1.4.0 start /Users/sam/electron-projects/iStats
> NODE_ENV=dev grunt & electron .

[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
Running "less:development" (less) task
>> 1 stylesheet created.

Running "watch" task
Waiting...

Would you suggest a solution to overcome this problem?
Thanks

**Comment by ningt** [comment]
`export EVENT_NOKQUEUE=1 && npm start` will eliminate these warnings, but actually they are harmless and app should start normally.

**Comment by 2sama** [comment]
Great, it works great now, thanks.
